### ISSUE TITLE
Amazon Multiple Images

### ISSUE THREAD

**Issue by ineffablep** [jonstuebe/scraper#3]
Hi, 
First of all this is great work.

I want to know how can I get multiple images in Slider.

**Comment by jonstuebe** [comment]
Feel free to fork the repo and add in additional fields. I'd love to have scraping definitions updated as well as more fields for each. I'll review any pr's that are opened. I just don't have a ton of time to dedicate to keeping things up-to-date. @wahengchang @ineffablep
